### ISSUE TITLE
Did you copy the sprites?

### ISSUE THREAD

**Issue by SunkyMP3G** [misterfirer/UrMod-mindustry-v7-#4]
Another mod stole just some of my sprites, and I dealed with it, but you stole all of them.

Original sprites: https://github.com/SunkyMP3G/Netronium/tree/Base/sprites
![image](https://github.com/misterfirer/UrMod-mindustry-v7-/assets/125795960/a4dbe9b6-3dc5-40af-bf32-71beb9f7d8a6)
![image](https://github.com/misterfirer/UrMod-mindustry-v7-/assets/125795960/c543dfd1-c163-4ca4-b69b-73c6decaa52a)

**Comment by misterfirer** [comment]
Yes,Sorry, it's me took the sprites. But I promise you, I will delete them soon, I just don't know how to draw sprites, but I have already learned a little. By the way, can you please make a list of sprites or take pictures of the ones I took from you? I will fix everything . Forgive me once again.

**Comment by misterfirer** [comment]
Pls ,sorry...

**Comment by justRive** [comment]
I can draw new sprites
