### ISSUE TITLE
I wanna help you

### ISSUE THREAD

**Issue by justRive** [misterfirer/UrMod-mindustry-v7-#6]
I like UrMod and I want that it was bigger and better. I want to _help_ you, for example, I have already made a new **sector** and some **new** buildings
If you need my help, write me on discord
If you don't, close it as not planned.

**Comment by DenisPlh** [comment]
****

**Comment by DenisPlh** [comment]
Still waiting answer

**Comment by DenisPlh** [comment]
I'm still waiting
(Yeah, yeah, yeah!)

**Comment by DenisPlh** [comment]
![logo](https://github.com/user-attachments/assets/5d67abe1-6db7-4a4e-b65e-135cca85bf74)

**Comment by DenisPlh** [comment]
I was bored, so I made a new logo
![logo](https://github.com/user-attachments/assets/f9d832f3-fcc4-4351-bb43-36d368ad679e)

**Comment by misterfirer** [comment]
Hello. What can I do so that you can help me?

**Comment by misterfirer** [comment]
Sorry for not replying for a long time.

**Comment by misterfirer** [comment]
Hello. What exactly can you help me with?

**Comment by justRive** [comment]
I made second sector, a new item, some new buildings and that's all. Well I can add something else if you want : )

**Comment by misterfirer** [comment]
Ok. Then I'm sorry that I didn't answer for a long time, I'm from Ukraine, I had a lot of problems, for example with electricity and so on. Therefore, I want to ask what is the best way to contact you?

**Comment by misterfirer** [comment]
If you are comfortable through discord, then let's do it through it.

**Comment by justRive** [comment]
Yes I am

**Comment by misterfirer** [comment]
Then I will send a friend request to discord now
